Repository ResidenciaTICBrisa/03_Robotica, pull requests merged in 2023-08, with the labels that each got.

#11 Adds scripts to compile and install ROS2
  ros2/.gitignore
  ros2/bootstrap-chroot-32.sh
  ros2/bootstrap-chroot-64.sh
  ros2/chroot-env-vars.sh
  ros2/compiling-for-amd64-based-systems.md
  ros2/compiling-for-arm-based-systems.md
  ros2/general-instructions.md
  ros2/installing-precompiled-packages.md
  ros2/ubuntu-compile-install-ros2-32.sh
  ros2/ubuntu-compile-install-ros2-64.sh
  ros2/ubuntu-compile-install-ros2-humble.sh
  ros2/ubuntu-install-ros2-64-base.sh
  ros2/ubuntu-install-ros2-64-desktop.sh
  ros2/ubuntu-install-ros2-humble-base.sh
  ros2/ubuntu-install-ros2-humble-desktop.sh
Labels: documentation, enhancement

#18 Add installation and compilation scripts for ROS1
  ros1/.gitignore
  ros1/bootstrap-chroot-32.sh
  ros1/bootstrap-chroot-64.sh
  ros1/chroot-env-vars.sh
  ros1/installing-native-packages.md
  ros1/installing-precompiled-packages.md
  ros1/ubuntu-compile-install-ros1-32.sh
  ros1/ubuntu-compile-install-ros1-64.sh
  ros1/ubuntu-compile-install-ros1-noetic.sh
  ros1/ubuntu-install-ros1-32-base.sh
  ros1/ubuntu-install-ros1-32-desktop.sh
  ros1/ubuntu-install-ros1-64-base.sh
  ros1/ubuntu-install-ros1-64-desktop-full.sh
  ros1/ubuntu-install-ros1-64-desktop.sh
  ros1/ubuntu-install-ros1-noetic-base.sh
  ros1/ubuntu-install-ros1-noetic-desktop-full.sh
  ros1/ubuntu-install-ros1-noetic-desktop.sh
Labels: documentation, enhancement

#27 Review ROS2 docs and add them to the website
  docs/mkdocs-kludge.sh
  docs/ros2/compiling-for-amd64-based-systems.md
  docs/ros2/compiling-for-arm-based-systems.md
  docs/ros2/general-instructions.md
  docs/ros2/installing-precompiled-packages.md
  mkdocs.yml
  ros2/compiling-for-amd64-based-systems.md
  ros2/compiling-for-arm-based-systems.md
  ros2/general-instructions.md
Labels: documentation

#45 Complete ros docs
  docs/mkdocs-kludge.sh
  docs/ros1/compiling-for-amd64-based-systems.md
  docs/ros1/compiling-for-arm-based-systems.md
  docs/ros1/general-instructions.md
  docs/ros1/installing-native-packages.md
  docs/ros1/installing-precompiled-packages.md
  docs/ros2/compiling-for-amd64-based-systems.md
  docs/ros2/compiling-for-arm-based-systems.md
  docs/ros2/general-instructions.md
  docs/ros2/installing-precompiled-packages.md
  ros1/.gitignore
  ros1/bootstrap-chroot-32.sh
  ros1/bootstrap-chroot-64.sh
  ros1/chroot-env-vars.sh
  ros1/compiling-for-amd64-based-systems.md
  ros1/compiling-for-arm-based-systems.md
  ros1/general-instructions.md
  ros1/installing-native-packages.md
  ros1/installing-precompiled-packages.md
  ros1/ubuntu-compile-install-ros1-32.sh
  ros1/ubuntu-compile-install-ros1-64.sh
  ros1/ubuntu-compile-install-ros1-noetic.sh
  ros1/ubuntu-install-ros1-32-base.sh
  ros1/ubuntu-install-ros1-32-desktop.sh
  ros1/ubuntu-install-ros1-64-base.sh
  ros1/ubuntu-install-ros1-64-desktop-full.sh
  ros1/ubuntu-install-ros1-64-desktop.sh
  ros1/ubuntu-install-ros1-noetic-base.sh
  ros1/ubuntu-install-ros1-noetic-desktop-full.sh
  ros1/ubuntu-install-ros1-noetic-desktop.sh
  ros2/.gitignore
  ros2/bootstrap-chroot-32.sh
  ros2/bootstrap-chroot-64.sh
  ros2/chroot-env-vars.sh
  ros2/compiling-for-amd64-based-systems.md
  ros2/compiling-for-arm-based-systems.md
  ros2/general-instructions.md
  ros2/installing-precompiled-packages.md
  ros2/ubuntu-compile-install-ros2-32.sh
  ros2/ubuntu-compile-install-ros2-64.sh
  ros2/ubuntu-compile-install-ros2-humble.sh
  ros2/ubuntu-install-ros2-64-base.sh
  ros2/ubuntu-install-ros2-64-desktop.sh
  ros2/ubuntu-install-ros2-humble-base.sh
  ros2/ubuntu-install-ros2-humble-desktop.sh
Labels: documentation, enhancement

#46 Move ROS scripts
  docs/mkdocs-kludge.sh
  docs/ros1/compiling-for-amd64-based-systems.md
  docs/ros1/compiling-for-arm-based-systems.md
  docs/ros1/general-instructions.md
  docs/ros1/installing-native-packages.md
  docs/ros1/installing-precompiled-packages.md
  docs/ros2/compiling-for-amd64-based-systems.md
  docs/ros2/compiling-for-arm-based-systems.md
  docs/ros2/general-instructions.md
  docs/ros2/installing-precompiled-packages.md
  mkdocs.yml
  scripts/ros1/.gitignore
  scripts/ros1/bootstrap-chroot-32.sh
  scripts/ros1/bootstrap-chroot-64.sh
  scripts/ros1/chroot-env-vars.sh
  scripts/ros1/compiling-for-amd64-based-systems.md
  scripts/ros1/compiling-for-arm-based-systems.md
  scripts/ros1/general-instructions.md
  scripts/ros1/installing-native-packages.md
  scripts/ros1/installing-precompiled-packages.md
  scripts/ros1/ubuntu-compile-install-ros1-32.sh
  scripts/ros1/ubuntu-compile-install-ros1-64.sh
  scripts/ros1/ubuntu-compile-install-ros1-noetic.sh
  scripts/ros1/ubuntu-install-ros1-32-base.sh
  scripts/ros1/ubuntu-install-ros1-32-desktop.sh
  scripts/ros1/ubuntu-install-ros1-64-base.sh
  scripts/ros1/ubuntu-install-ros1-64-desktop-full.sh
  scripts/ros1/ubuntu-install-ros1-64-desktop.sh
  scripts/ros1/ubuntu-install-ros1-noetic-base.sh
  scripts/ros1/ubuntu-install-ros1-noetic-desktop-full.sh
  scripts/ros1/ubuntu-install-ros1-noetic-desktop.sh
  scripts/ros2/.gitignore
  scripts/ros2/bootstrap-chroot-32.sh
  scripts/ros2/bootstrap-chroot-64.sh
  scripts/ros2/chroot-env-vars.sh
  scripts/ros2/compiling-for-amd64-based-systems.md
  scripts/ros2/compiling-for-arm-based-systems.md
  scripts/ros2/general-instructions.md
  scripts/ros2/installing-precompiled-packages.md
  scripts/ros2/ubuntu-compile-install-ros2-32.sh
  scripts/ros2/ubuntu-compile-install-ros2-64.sh
  scripts/ros2/ubuntu-compile-install-ros2-humble.sh
  scripts/ros2/ubuntu-install-ros2-64-base.sh
  scripts/ros2/ubuntu-install-ros2-64-desktop.sh
  scripts/ros2/ubuntu-install-ros2-humble-base.sh
  scripts/ros2/ubuntu-install-ros2-humble-desktop.sh
Labels: documentation, enhancement

#48 Adição de instruções e fixes.
  docs/Instruções/CPP_SDK_v4.md
  docs/Instruções/CPP_SDK_v6.md
  docs/Instruções/Choregraphe_v4.md
  docs/Instruções/Choregraphe_v6.md
  docs/Instruções/Maquina_Virtual.md
  docs/Instruções/NAO_Flasher.md
  docs/Instruções/ROS_1.md
  docs/Instruções/Robot_Settings.md
  docs/index.md
  mkdocs.yml
Labels: bug, documentation, NAOv4
