Repository ResidenciaTICBrisa/03_Robotica, pull requests merged in 2023-11, with the labels that each got.

#81 Explica como adiciona arquivos às VMs e como usar o robô simulado e corrige problemas de navegação
  docs/vms/ubuntu-14/README.md
  docs/vms/ubuntu-14/how-to-use.md
  docs/vms/ubuntu-16/README.md
  docs/vms/ubuntu-16/how-to-use.md
  mkdocs.yml
  scripts/vms/ubuntu-14/how-to-use.md
  scripts/vms/ubuntu-16/how-to-use.md
Labels: bug, documentation, NAOv4, NAOv6

#83 Fix da page
  docs/Instruções/Choregraphe_v4.md
  docs/Instruções/Choregraphe_v6.md
  docs/Instruções/Conceitos_Gerais.md
  docs/Instruções/Maquina_Virtual.md
  docs/Instruções/NAO_Flasher.md
  docs/Instruções/NAOqi-overview_v4.md
  docs/Instruções/NAOqi-overview_v6.md
  docs/Instruções/Robot_Settings.md
  docs/overrides/assets/images/IMG_NAO.jpg
  docs/overrides/equipe.html
  docs/overrides/home.html
  docs/release/index.md
  docs/sobre/equipe.md
  mkdocs.yml
  nao-programs/naoqi-2.1/cpp/about-the-examples.md
Labels: bug, documentation

#91 Traduzir documentação relativa ao NAOv4
  docs/naoqi-2.1/cpp/about-the-examples-en.md
  docs/naoqi-2.1/cpp/about-the-examples-ptbr.md
  docs/vms/ubuntu-14/how-to-use-en.md
  docs/vms/ubuntu-14/how-to-use-ptbr.md
  nao-programs/naoqi-2.1/cpp/about-the-examples-en.md
  nao-programs/naoqi-2.1/cpp/about-the-examples-ptbr.md
  nao-programs/naoqi-2.1/cpp/about-the-examples.md
  scripts/vms/ubuntu-14/how-to-use-en.md
  scripts/vms/ubuntu-14/how-to-use-ptbr.md
  scripts/vms/ubuntu-14/how-to-use.md
Labels: documentation, NAOv4

#93 Poo
  docs/Instruções/Guia_POO.md
  docs/overrides/assets/images/Circuito_interno.jpg
  docs/overrides/assets/images/Classe_Objeto.jpg
  docs/overrides/assets/images/Classe_final.jpg
  docs/overrides/assets/images/Encapsulamento.jpg
  docs/overrides/assets/images/Esquematico_get.jpg
  mkdocs.yml
Labels: documentation, NAOv4, NAOv6
